# -*- coding: utf-8 -*-
"""Test1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFbifO0JOidu2drSALZxKZ3VPYlyMYZP
"""

#1
length=float(input("enter the length"))
width=float(input("enter the width"))
area=length*width
print("THE AREA OF RECTANGLE IS ",area)

#2
weight=float(input("enter the weight in kg"))
height=float(input("enter the height in m"))
bmi=(weight/height**2)
print("THE BMI IS ",bmi)

#3
student={}
i='y'
while(i=='y'):
  name=input("ENTER THE NAME ")
  score=input("ENTER THE SCORES ")
  i=input("ENTER Y TO ADD OTHER STUDENT INFORMATION ").lower()
  student={"name":name,"score":score}
print(student)

#4
age=int(input("ENTER THE AGE "))
if(age<18):
  print("MINOR")
elif(age>=18 and age<65):
  print("ADULT")
else:
  print("SENIOR")

#5

for i in range(2,50,2):
  print(i)

#6
def password():

    correct_password = "Harish@23"

    while(1):

        password_attempt = input("Enter the password: ")
        if password_attempt == correct_password:
            print("Welcome!!!!")
            break
        else:
            print("Incorrect password. Try again.")

password()

#7
number=[1,2,3,4,5]

sum=0
for x in number:
  sum=sum+x
average=sum/len(number)
print("AVERAGE ",average)

#8
def vowels(string):
    vowels = "aeiouAEIOU"
    count = 0
    for char in string:
        if char in vowels:
            count =count+ 1
    return count


x =str(input("ENTER THE STRING"))
print("Number of vowels:", vowels(x))

#9
from datetime import datetime
export_datetime=datetime.now()

date=export_datetime.date()
time=export_datetime.time()
print("THE CURRENT DATE IS ",date)
print("THE CURRENT TIME IS ",time)

#10
 def numeric(a, b):
    try:
        result = float(a) + float(b)
        return result
    except ValueError:
        return "Non-numeric input detected!"


num1 = input("Enter the  number1: ")
num2 = input("Enter the  number2: ")

print(numeric(num1, num2))

#11
try:
    a = int(input('Enter an integer value'))
    print(a)
except ValueError:
    print('The value cannot be a non integer')

#12
def division_function(a,b):
    try:
        return b/a
    except ZeroDivisionError:
        print('Division by zero is not possible')

#13
f = open('Python.txt','w')
f.writelines('Hello,Python!')

#14
f = open('Python.txt','r')
f.readlines()

#15
f = open('Python.txt','a')
f.writelines('HI nice to see you here')

f = open('Python.txt','r')
f.readlines()